name: 'Upload Episode from YouTube To Anchor.Fm'
description: 'An automation tool to publish your podcast from youtube to anchor.fm'
branding:
  icon: 'upload-cloud'  
  color: 'green'
runs:
  using: "docker"
  image: "docker://docker.io/weltonrodrigo/youtubetoanchor:multi-show"
